export const CREATE_CHANNEL_REQUEST = "CREATE_CHANNEL_REQUEST";
export const CREATE_CHANNEL_SUCCESS = "CREATE_CHANNEL_SUCCESS";
export const CREATE_CHANNEL_FAIL = "CREATE_CHANNEL_FAIL";

export const GET_ALL_CHANNELS_REQUEST = "GET_ALL_CHANNELS_REQUEST";
export const GET_ALL_CHANNELS_SUCCESS = "GET_ALL_CHANNELS_SUCCESS";
export const GET_ALL_CHANNELS_FAIL = "GET_ALL_CHANNELS_FAIL";

export const GET_SELECTED_CHANNEL_REQUEST = "GET_SELECTED_CHANNEL_REQUEST";
export const GET_SELECTED_CHANNEL_SUCCESS = "GET_SELECTED_CHANNEL_SUCCESS";
export const GET_SELECTED_CHANNEL_FAIL = "GET_SELECTED_CHANNEL_FAIL";

export const JOIN_CHANNEL_REQUEST = "JOIN_CHANNEL_REQUEST";
export const JOIN_CHANNEL_SUCCESS = "JOIN_CHANNEL_SUCCESS";
export const JOIN_CHANNEL_FAIL = "JOIN_CHANNEL_FAIL";

export const GET_MESSAGES_REQUEST = "GET_MESSAGES_REQUEST";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAIL = "GET_MESSAGES_FAIL";
